# Generated by Django 5.0.6 on 2024-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_runner_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='position',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=30),
        ),
    ]
