# Generated by Django 5.0.6 on 2024-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_runner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(help_text='Enter caps', max_length=50),
        ),
    ]
