# Generated by Django 5.0.6 on 2024-07-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_musician_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runner',
            options={'verbose_name_plural': 'Runneres'},
        ),
    ]
